services:
  tester:
    depends_on:
      ldap:
        condition: service_healthy
      sso:
        condition: service_healthy
    environment:
      - CAS_CONTAINER=sso
  ldap:
    image: gunet/simple-ldap
    environment:
      - TZ=Europe/Athens
    restart: unless-stopped
  sso:
    image: gunet/simple-cas
    ports:
      - 8443:8443
    depends_on:
      ldap:
        condition: service_healthy
    restart: unless-stopped
    environment:
      - LDAP_URL=ldap://ldap:1389
      - CAS_SERVER_NAME=${CAS_SERVER_NAME:-https://localhost:8443}
