version: '3.7'

services:
  tester:
    depends_on:
      - ldap
      - sso
    volumes:
      - ./code:/var/www/html
    environment:
      - CAS_CONTAINER=sso
  ldap:
    image: gunet/simple-ldap
    environment:
      - TZ=Europe/Athens
    restart: unless-stopped
  sso:
    image: gunet/simple-cas
    ports:
      - "8443:8443"
    depends_on:
      - ldap
    restart: unless-stopped
    environment:
      - TZ=Europe/Athens
      - LDAP_URL=ldap://ldap:1389
      - CAS_SERVER_NAME=${CAS_SERVER_NAME:-https://localhost:8443}
