name: image-build
run-name: Build phpcas-tester Docker image

on:
  workflow_dispatch:
  push:
    branches:
      - "main"
    paths:
      - 'Dockerfile'
      - 'apache/**'
      - 'certs/**'
      - 'code/**'
      - 'php/**'

jobs:
  image-build:
    runs-on: ubuntu-latest
    steps:
      - name: Set timezone
        uses: zcong1993/setup-timezone@master
        with:
          timezone: "Europe/Athens"
      - name: Get date
        id: date
        run: echo "push_date=$(date '+%H:%M@%d/%m/%Y')" >> $GITHUB_ENV
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push Base image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: gunet/phpcas-tester:latest
          labels: gr.gunet.phpcas-tester.pushdate=${{ env.push_date }}
          cache-from: type=gha
          cache-to: type=gha,mode=max